<a href="https://colab.research.google.com/github/ShaileshKrCh/Machine_Learning/blob/main/Numpy_Classwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy:Numeric Python**
**Numpy** is an extennsion to the Python programming language, adding support for large, multi-dimensional (numerical) arrays and matrics, along with a large library of high-level mathematical functions to operate on those arrays. The full form of NumPy is Numeric Python.

In [2]:
#importing required modules
import numpy as np

In [ ]:
print(np.__version__)

2.0.2


In [ ]:
#creating ndarray from lists
#note:array elements must be of the same data type
data1 =[11,22,3,3,44,444,555,5556]  ## homogeneous datatype for list elements
print(data1,len(data1),type(data1))
arr1=np.array(data1)
print(arr1,len(arr1),type(arr1),arr1.dtype)  # len gives the first dimension


[11, 22, 3, 3, 44, 444, 555, 5556] 8 <class 'list'>
[  11   22    3    3   44  444  555 5556] 8 <class 'numpy.ndarray'> int64


In [3]:
data1 = (11, 22, "AEC", 33.5, 44, 55, 66, True, False)  # heterogeneous datatype for list elements
print(data1, len(data1), type(data1))
arr1 = np.array(data1)
print(arr1, len(arr1), type(arr1), arr1.dtype)  # len gives the first dimension

(11, 22, 'AEC', 33.5, 44, 55, 66, True, False) 9 <class 'tuple'>
['11' '22' 'AEC' '33.5' '44' '55' '66' 'True' 'False'] 9 <class 'numpy.ndarray'> <U32


In [5]:
data1 ={11,22,"AEC",3,44,444,555,5556,True,False}
print(data1,len(data1),type(data1))
arr1=np.array(data1)
print(arr1,type(arr1),arr1.dtype)

{False, True, 3, 11, 44, 555, 'AEC', 5556, 22, 444} 10 <class 'set'>
{False, True, 3, 11, 44, 555, 'AEC', 5556, 22, 444} <class 'numpy.ndarray'> object


In [8]:
data1 =[11,22,"AEC",3,44,444,555,5556,True,False]
print(data1,len(data1),type(data1))
arr1=np.array(data1)
print(arr1,len(arr1),type(arr1),arr1.dtype)

[11, 22, 'AEC', 3, 44, 444, 555, 5556, True, False] 10 <class 'list'>
['11' '22' 'AEC' '3' '44' '444' '555' '5556' 'True' 'False'] 10 <class 'numpy.ndarray'> <U21


In [9]:
print(range(1, 10), list(range(1, 10)))
list1 = [range(1, 5), range(6, 10)]  # list of lists
print(list1)
arr2 = np.array(list1)
print(arr2, len(arr2), type(arr2), arr2.dtype)  # 2-dimensional array
for item in np.nditer(arr2):  # displaying the content of the ndarray
    print(item, end = ", ")

range(1, 10) [1, 2, 3, 4, 5, 6, 7, 8, 9]
[range(1, 5), range(6, 10)]
[[1 2 3 4]
 [6 7 8 9]] 2 <class 'numpy.ndarray'> int64
1, 2, 3, 4, 6, 7, 8, 9, 

In [10]:
print(arr1)
print(arr2)
print(arr1.tolist())
print(list(arr1))
print(arr2.tolist())
print(list(arr2))

['11' '22' 'AEC' '3' '44' '444' '555' '5556' 'True' 'False']
[[1 2 3 4]
 [6 7 8 9]]
['11', '22', 'AEC', '3', '44', '444', '555', '5556', 'True', 'False']
[np.str_('11'), np.str_('22'), np.str_('AEC'), np.str_('3'), np.str_('44'), np.str_('444'), np.str_('555'), np.str_('5556'), np.str_('True'), np.str_('False')]
[[1, 2, 3, 4], [6, 7, 8, 9]]
[array([1, 2, 3, 4]), array([6, 7, 8, 9])]


# **Examining Arrays**

In [ ]:
arr1=np.array([11,22,33,44,55,66,77,88])
print(arr1,type(arr1),len(arr1),id(arr1))
print(arr1.ndim,arr1.shape,arr1.size,arr1.dtype,arr1.itemsize,arr1.nbytes)

[11 22 33 44 55 66 77 88] <class 'numpy.ndarray'> 8 132391544879888
1 (8,) 8 int64 8 64


In [ ]:
arr2=np.array([[11,22,33,44,55,66,77,88],[11,22,33,44,55,66,77,88]])
print(arr2,type(arr2),len(arr2),id(arr2))
print(arr2.ndim, arr2.shape, arr2.size, arr2.dtype,arr2.itemsize, arr2.nbytes)

[[11 22 33 44 55 66 77 88]
 [11 22 33 44 55 66 77 88]] <class 'numpy.ndarray'> 2 132391545282000
2 (2, 8) 16 int64 8 128


In [14]:
var=(8)
print(var,type(var))
var=(8,) # singleton representation of a tuple
print(var,type(var))

8 <class 'int'>
(8,) <class 'tuple'>


# **Creating special Array**

In [19]:
print(np.zeros(10),np.zeros(10).dtype)
print(np.zeros(10,dtype=np.int8),np.zeros(10,dtype=np.int8).dtype)
print(np.zeros(10).astype(int),np.zeros(10).astype(np.int8),np.zeros(10).astype(np.int8).dtype)
print("\n")
print(np.zeros((2,5)))
print("\n")
print(np.zeros((2,5),dtype=np.int16))
print("\n")
print(np.zeros(10,dtype=np.int16).reshape(2,5))
print("\n")
print(np.zeros(10,dtype=np.int16).reshape(1,10))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64
[0 0 0 0 0 0 0 0 0 0] int8
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0] int8


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[0 0 0 0 0]
 [0 0 0 0 0]]


[[0 0 0 0 0]
 [0 0 0 0 0]]


[[0 0 0 0 0 0 0 0 0 0]]


In [ ]:
print(np.ones(10),np.zeros(10).dtype)
print(np.ones(10,dtype=np.int8),np.zeros(10,dtype=np.int8).dtype)
print(np.ones(10).astype(int),np.zeros(10).astype(np.int8),np.zeros(10).astype(np.int8).dtype)
print(np.ones((2,5)))
print(np.ones((2,5),dtype=np.int16))
print(np.ones(10,dtype=np.int16).reshape(2,5))
print(np.ones(10,dtype=np.int16).reshape(1,10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64
[1 1 1 1 1 1 1 1 1 1] int8
[1 1 1 1 1 1 1 1 1 1] [0 0 0 0 0 0 0 0 0 0] int8
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1 1 1 1 1 1]]


In [ ]:
print(np.zeros(10) + 6)
print(np.ones(10) + 6)
print(np.ones(10) * 6)


[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]


In [20]:
print(np.linspace(0,1,5)) #(range 0 to 1 in 5 equal parts)
print(np.linspace(1,10,19))

[0.   0.25 0.5  0.75 1.  ]
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [25]:
print(np.logspace(0,3,4)) # by default base 10 range 0 to 10 power 3
print(np.logspace(0,3,4,base=3))
print(np.logspace(0,3,4,base=10))
print(np.logspace(0,10))

[   1.   10.  100. 1000.]
[ 1.  3.  9. 27.]
[   1.   10.  100. 1000.]
[1.00000000e+00 1.59985872e+00 2.55954792e+00 4.09491506e+00
 6.55128557e+00 1.04811313e+01 1.67683294e+01 2.68269580e+01
 4.29193426e+01 6.86648845e+01 1.09854114e+02 1.75751062e+02
 2.81176870e+02 4.49843267e+02 7.19685673e+02 1.15139540e+03
 1.84206997e+03 2.94705170e+03 4.71486636e+03 7.54312006e+03
 1.20679264e+04 1.93069773e+04 3.08884360e+04 4.94171336e+04
 7.90604321e+04 1.26485522e+05 2.02358965e+05 3.23745754e+05
 5.17947468e+05 8.28642773e+05 1.32571137e+06 2.12095089e+06
 3.39322177e+06 5.42867544e+06 8.68511374e+06 1.38949549e+07
 2.22299648e+07 3.55648031e+07 5.68986603e+07 9.10298178e+07
 1.45634848e+08 2.32995181e+08 3.72759372e+08 5.96362332e+08
 9.54095476e+08 1.52641797e+09 2.44205309e+09 3.90693994e+09
 6.25055193e+09 1.00000000e+10]


In [ ]:
help(np.logspace)

Help on _ArrayFunctionDispatcher in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.

    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.25.0
        Non-scalar 'base` is now supported

    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boo

In [ ]:
print(np.arange(10), type(np.arange(10)))
print(np.arange(1, 10, 2), type(np.arange(10)))
print(np.arange(-10, 10), type(np.arange(10)))
print(np.arange(0, 50).reshape(5, 10))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[1 3 5 7 9] <class 'numpy.ndarray'>
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9] <class 'numpy.ndarray'>
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


#**Reshape**

In [ ]:
arr1 =np.arange(1,21)
print(arr1,arr1.shape)
print(arr1.reshape(4,5).astype(np.float16))
print(arr1.astype(np.float16).reshape(4,5))
print(arr1.astype(np.float16).reshape(4,-1))
print(arr1.astype(np.float16).reshape(-1,5))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] (20,)
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]


In [ ]:
arr1=np.arange(1,21)
print(arr1,arr1.shape)
print(arr1.reshape(2,2,5).astype(np.float16))
print(arr1.reshape(2,-1,5).astype(np.float16))
print(arr1.reshape(2,2,-1).astype(np.float16))#we can put -1 in any place they are giving same output

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] (20,)
[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]]

 [[11. 12. 13. 14. 15.]
  [16. 17. 18. 19. 20.]]]
[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]]

 [[11. 12. 13. 14. 15.]
  [16. 17. 18. 19. 20.]]]
[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]]

 [[11. 12. 13. 14. 15.]
  [16. 17. 18. 19. 20.]]]


In [ ]:
arr1=np.arange(1,21).reshape(4,5)
print(arr1)
print(arr1.T) #transpose
print(arr1.transpose()) #transpose
print(arr1.flatten()) #multi dimensional to 1 dimensional

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
arr1=np.arange(1,21).reshape(4,5)
print(arr1)
arr1=arr1.T
print(arr1)
print(arr1.flatten())
print(arr1.reshape(20))
print(arr1.reshape(20,1))
print(arr1.reshape(1,20))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
[ 1  6 11 16  2  7 12 17  3  8 13 18  4  9 14 19  5 10 15 20]
[ 1  6 11 16  2  7 12 17  3  8 13 18  4  9 14 19  5 10 15 20]
[[ 1]
 [ 6]
 [11]
 [16]
 [ 2]
 [ 7]
 [12]
 [17]
 [ 3]
 [ 8]
 [13]
 [18]
 [ 4]
 [ 9]
 [14]
 [19]
 [ 5]
 [10]
 [15]
 [20]]
[[ 1  6 11 16  2  7 12 17  3  8 13 18  4  9 14 19  5 10 15 20]]


In [ ]:
matrix = np.arange(10,dtype=np.float16).reshape(2,5)
print(matrix)
print("\nstored in default order(Row major):")
for item in np.nditer(matrix):
    print(item,end=",")
print("\n\nstored in C-style order(Row major):")
cmatrix=matrix.copy(order="C")
for item in np.nditer(cmatrix):
    print(item,end=",")
print("\n\nstored in F-style order(Column major):")
fmatrix=matrix.copy(order="F")
for item in np.nditer(fmatrix):
    print(item,end=",")


[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]

stored in default order(Row major):
0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,

stored in C-style order(Row major):
0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,

stored in F-style order(Column major):
0.0,5.0,1.0,6.0,2.0,7.0,3.0,8.0,4.0,9.0,

#**Append ,Insert,Delete,and Sort**

In [ ]:
matrix = np.arange(11,100,11,dtype=np.int8)
print(matrix,matrix.shape)
matrix=np.append(matrix,np.array([110,120,130]))
print(matrix,matrix.shape)
matrix=np.insert(matrix,3,[100,200,300])
print(matrix,matrix.shape)
matrix=np.insert(matrix,len(matrix),[800,900])
print(matrix,matrix.shape)
matrix=np.delete(matrix,range(3,7))
print(matrix,matrix.shape)
matrix=np.delete(matrix,[9,2,5])
print(matrix,matrix.shape)
matrix=np.sort(matrix)
print(matrix,matrix.shape)


[11 22 33 44 55 66 77 88 99] (9,)
[ 11  22  33  44  55  66  77  88  99 110 120 130] (12,)
[ 11  22  33 100 200 300  44  55  66  77  88  99 110 120 130] (15,)
[ 11  22  33 100 200 300  44  55  66  77  88  99 110 120 130 800 900] (17,)
[ 11  22  33  55  66  77  88  99 110 120 130 800 900] (13,)
[ 11  22  55  66  88  99 110 130 800 900] (10,)
[ 11  22  55  66  88  99 110 130 800 900] (10,)


In [ ]:
matrix = np.array([100,399,578,89,76,754,900])
print(matrix,matrix.shape)
matrix_sort=np.sort(matrix)
print(matrix_sort,matrix_sort.shape)
matrix_sort=-np.sort(-matrix)
print(matrix_sort,matrix_sort.shape)

[100 399 578  89  76 754 900] (7,)
[ 76  89 100 399 578 754 900] (7,)
[900 754 578 399 100  89  76] (7,)


#**Contatenation and Stack of Two Arrays**

In [ ]:
arr1=np.array([[11,22],[34,55]])
print(arr1,arr1.shape)
arr2=np.array([[66,77],[88,99]])
print(arr2,arr2.shape)
#both the arrays are of the same dimensions
print("Joining the two arrays along axis 0(Rows wise):") # by default axis=0
print(np.concatenate((arr1,arr2)))
print("Joining the two arrays along axis 1:")
print(np.concatenate((arr1,arr2),axis=1))

[[11 22]
 [34 55]] (2, 2)
[[66 77]
 [88 99]] (2, 2)
Joining the two arrays along axis 0:
[[11 22]
 [34 55]
 [66 77]
 [88 99]]
Joining the two arrays along axis 0:
[[11 22 66 77]
 [34 55 88 99]]


In [ ]:
print("stack the two arraus along axis 0(Rows wise):")
print(np.stack((arr1,arr2),axis=0))
print("stack the two arraus along axis 1:")
print(np.stack((arr1,arr2),axis=1))
print(np.stack((arr1,arr2),axis=1))
print(np.stack((arr1,arr2),axis=1).shape)



stack the two arraus along axis 0(Rows wise):
[[[11 22]
  [34 55]]

 [[66 77]
  [88 99]]]
stack the two arraus along axis 1:
[[[11 22]
  [66 77]]

 [[34 55]
  [88 99]]]
[[[11 22]
  [66 77]]

 [[34 55]
  [88 99]]]
(2, 2, 2)


#**Selection**


In [ ]:
arr2 =np.arange(20).reshape(4,5)
print(arr2,arr2.shape)
print(arr2[2,3],arr2[2][3],arr2[-2][-2],arr2[2][-2],arr2[-2][3]) #indexing
print(arr2[1:3,:]) # Slicing
print(arr2[1:3,:])
print(arr2[:,3:5])
print(arr2[:,2:4])
print(arr2[1:3,1:5])
print(arr2[-4:-2,-4:-1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)
13 13 13 13 13
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]]
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]
[[ 6  7  8  9]
 [11 12 13 14]]
[[1 2 3]
 [6 7 8]]


In [ ]:
arr1=np.zeros(25).reshape(5,5)
# print(arr1)
arr1[0:1,]=10
# print(arr1)
arr1[:,0:1]=10
arr1[1:0,]=10
arr1[4:5,]=10
arr1[:,4:5]=10
print(arr1)

[[10. 10. 10. 10. 10.]
 [10.  0.  0.  0. 10.]
 [10.  0.  0.  0. 10.]
 [10.  0.  0.  0. 10.]
 [10. 10. 10. 10. 10.]]


In [ ]:
arr2 = np.zeros(36).reshape(6,6)
arr2[[0, -1], :] = 10
arr2[:, [0, -1]] = 10
print(arr2)

[[10. 10. 10. 10. 10. 10.]
 [10.  0.  0.  0.  0. 10.]
 [10.  0.  0.  0.  0. 10.]
 [10.  0.  0.  0.  0. 10.]
 [10.  0.  0.  0.  0. 10.]
 [10. 10. 10. 10. 10. 10.]]


In [ ]:
arr2 = np.ones(36).reshape(6,6) * 10
arr2[1:-1, 1:-1] = 0
print(arr2)

[[10. 10. 10. 10. 10. 10.]
 [10.  0.  0.  0.  0. 10.]
 [10.  0.  0.  0.  0. 10.]
 [10.  0.  0.  0.  0. 10.]
 [10.  0.  0.  0.  0. 10.]
 [10. 10. 10. 10. 10. 10.]]


#**Views and Copies**

In [ ]:
arr1=np.arange(10)
print(arr1,arr1[5:8])
arr1[5:8]=22
print(arr1)
arr_views=arr1[5:8] #creating a view
print(arr_views)
arr_views[:]=33
print(arr1)
print(arr_views)

[0 1 2 3 4 5 6 7 8 9] [5 6 7]
[ 0  1  2  3  4 22 22 22  8  9]
[22 22 22]
[ 0  1  2  3  4 33 33 33  8  9]
[33 33 33]


In [ ]:
arr1=np.arange(10)
print(arr1,arr1[5:8])
arr_copy=arr1[5:8].copy() #creating a copy
arr1[5:8]=22
print(arr1)
arr_copy=arr1[5:8] #creating a copies
print(arr_copy)
arr_copy[:]=33
print(arr1)
print(arr_copy)

[0 1 2 3 4 5 6 7 8 9] [5 6 7]
[ 0  1  2  3  4 22 22 22  8  9]
[22 22 22]
[ 0  1  2  3  4 33 33 33  8  9]
[33 33 33]


In [ ]:
list1 =[11,22,33,44,55,66]
list2=list1 #view
print(list1,list2)
list1[3]=90
print(list1,list2)
list2[:]
list2=list1[:] #copy
list1[5]=500
print(list1,list2)


[11, 22, 33, 44, 55, 66] [11, 22, 33, 44, 55, 66]
[11, 22, 33, 90, 55, 66] [11, 22, 33, 90, 55, 66]
[11, 22, 33, 90, 55, 500] [11, 22, 33, 90, 55, 66]


##**Using Boolean  Arrays**


In [ ]:
arr1 =np.array([10,-45,40,-44,-56,60,80,-55])
print(arr1,arr1.shape)
print(arr1 >= 0) #generating one boolean array
print(arr1[arr1 >= 0])
print(~(arr1 >= 0)) # generating one boolean array
print(arr1[~(arr1 >= 0)])
print((arr1<-50) | (arr1>50))
print(arr1[(arr1<-50) | (arr1>50)])
print(arr1[(arr1 % 2 == 0)])
print(arr1[~(arr1 % 2 == 0)])

[ 10 -45  40 -44 -56  60  80 -55] (8,)
[ True False  True False False  True  True False]
[10 40 60 80]
[False  True False  True  True False False  True]
[-45 -44 -56 -55]
[False False False False  True  True  True  True]
[-56  60  80 -55]
[ 10  40 -44 -56  60  80]
[-45 -55]


In [ ]:
arr1 =np.array([10,-45,40,-44,-56,60,80,-55])
print(arr1,arr1.shape)
print(arr1[(arr1% 4==0)&(arr1% 5==0)])
print(arr1[~((arr1% 4==0)&(arr1% 5==0))])

[ 10 -45  40 -44 -56  60  80 -55] (8,)
[40 60 80]
[ 10 -45 -44 -56 -55]


In [ ]:
arr1 =np.array(['bob','pat','joe','will','bob','joe','joe'])
print(arr1,arr1.shape)
print(arr1 != 'bob')
print(arr1[arr1 != 'bob'])
arr1[arr1 == 'bob']='jam'
print(arr1)
print(np.unique(arr1)) #getting all unique names




['bob' 'pat' 'joe' 'will' 'bob' 'joe' 'joe'] (7,)
[False  True  True  True False  True  True]
['pat' 'joe' 'will' 'joe' 'joe']
['jam' 'pat' 'joe' 'will' 'jam' 'joe' 'joe']
['jam' 'joe' 'pat' 'will']


In [ ]:
mystr ="mississippi"
print(mystr , list(mystr))
arr1=np.array(list(mystr))
print(np.unique(arr1))
print(set(list(mystr)))
print(set(mystr))

mississippi ['m', 'i', 's', 's', 'i', 's', 's', 'i', 'p', 'p', 'i']
['i' 'm' 'p' 's']
{'s', 'p', 'i', 'm'}
{'s', 'p', 'i', 'm'}


In [ ]:
mystr = "    university      "
print(mystr, len(mystr))
print(mystr.lstrip(), len(mystr.lstrip()))
print(mystr.rstrip(), len(mystr.rstrip()))
print(mystr.strip(), len(mystr.strip()))

    university       20
university       16
    university 14
university 10


In [ ]:
mystr = "@@#@university@@@#@"
print(mystr, len(mystr))
print(mystr.lstrip("#@"), len(mystr.lstrip("#@")))
print(mystr.rstrip("#@"), len(mystr.rstrip("#@")))
print(mystr.strip("#@"), len(mystr.strip("#@")))

@@#@university@@@#@ 19
university@@@#@ 15
@@#@university 14
university 10


#**Vector Operations**

In [ ]:
arr1 = np.arange(10)
print(arr1)
print(arr1+100)
print(arr1*100)
print(np.sqrt(arr1))
print(np.ceil(np.sqrt(arr1)))
print(np.floor(np.sqrt(arr1)))
print(np.round(np.sqrt(arr1)))

[0 1 2 3 4 5 6 7 8 9]
[100 101 102 103 104 105 106 107 108 109]
[  0 100 200 300 400 500 600 700 800 900]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0. 1. 2. 2. 2. 3. 3. 3. 3. 3.]
[0. 1. 1. 1. 2. 2. 2. 2. 2. 3.]
[0. 1. 1. 2. 2. 2. 2. 3. 3. 3.]


In [ ]:
import numpy as np
import math
var1 = np.array([11,22,33,44,55,66,77])
var2=100
print(np.sqrt(var1),np.sqrt(var2))
print(math.sqrt(var2))

[3.31662479 4.69041576 5.74456265 6.63324958 7.41619849 8.1240384
 8.77496439] 10.0
10.0


In [ ]:
arr1 =np.arange(10)
print(arr1)
arr2=np.arange(20,30)
print(arr2,arr2.shape)
print(arr1+arr2)
print(arr1*arr2)

[0 1 2 3 4 5 6 7 8 9]
[20 21 22 23 24 25 26 27 28 29] (10,)
[20 22 24 26 28 30 32 34 36 38]
[  0  21  44  69  96 125 156 189 224 261]


In [ ]:
arr1 = np.array([100,200,np.nan,300,600,500,np.nan])
print(arr1,arr1.shape)
print(np.isnan(arr1))
print(arr1[~np.isnan(arr1)])

[100. 200.  nan 300. 600. 500.  nan] (7,)
[False False  True False False False  True]
[100. 200. 300. 600. 500.]


In [ ]:
arr1=np.array([100,-200,300,400,-500,600,700])
print(arr1,arr1.shape)
arr2 =np.array([11,-800,54,66,778,55,-48])
print(arr2,arr2.shape)
print(np.maximum(arr1,arr2))
print(np.minimum(arr1,arr2))
print(np.argmax(arr1),np.argmax(arr2))
print(np.argmin(arr1),np.argmin(arr2))


[ 100 -200  300  400 -500  600  700] (7,)
[  11 -800   54   66  778   55  -48] (7,)
[ 100 -200  300  400  778  600  700]
[  11 -800   54   66 -500   55  -48]
6 4
4 1


In [ ]:
vect1 =np.random.randn(9000)
print(vect1[:10],vect1.shape)
print(np.average(vect1),np.std(vect1))
vect2 =np.random.randn(9000)
print(vect2[:10],vect2.shape)
print(np.maximum(vect1,vect2))

[ 0.39599438 -0.46883748 -0.09971376 -2.48266206 -0.28526752  1.04186772
 -0.57585762  0.14265407  0.57824799 -0.02168238] (9000,)
0.009111377270538635 0.9908196894443186
[ 1.68585628 -1.00766102 -1.19239969  0.0505004  -0.42148558  0.07555979
 -0.49669129 -0.03072212 -0.58788363 -1.69043567] (9000,)
[ 1.68585628 -0.46883748 -0.09971376 ...  1.0456665   0.50780426
 -0.06565401]


In [ ]:
# Eucledian distance
vect1 = np.random.randn(10)
vect2 = np.random.randn(10)
# pt1(x1, y1), pt2(x2, y2) => sqrt((x1 - y1)^2 + (x2 - y2)^2)
dist = 0
for i in range(len(vect1)):
    dist = dist + (vect1[i] - vect2[i]) ** 2
print(np.sqrt(dist))
print(np.sqrt(np.sum((vect1 - vect2) ** 2)))
print(np.sqrt(np.sum(pow(np.subtract(vect1, vect2), 2))))

3.608953060880621
3.6089530608806206
3.6089530608806206


In [ ]:
np.random.seed(101)
vect1 =np.random.randn(10)
print(vect1,vect1.shape)
vect1 =np.random.rand(10)
print(vect1,vect1.shape)
vect1 =np.random.randint(0,2,10)
print(vect1,vect1.shape)

[ 2.70684984  0.62813271  0.90796945  0.50382575  0.65111795 -0.31931804
 -0.84807698  0.60596535 -2.01816824  0.74012206] (10,)
[0.1818924  0.78560176 0.96548322 0.23235366 0.08356143 0.60354842
 0.72899276 0.27623883 0.68530633 0.51786747] (10,)
[0 1 1 1 1 0 0 0 1 1] (10,)


In [ ]:
vect1 = np.random.randn(10)
print(vect1)
print(vect1 > 0)
print((vect1 > 0).sum())
print((vect1 > 0).any())
print((vect1 > 0).all())
print(~((vect1 > 0).any()))

[ 1.65207044  0.19692527  0.10321419 -0.14737026  1.13128366  1.08583909
  0.44948591 -0.00296292 -0.64817706 -0.95614981]
[ True  True  True False  True  True  True False False False]
6
True
False
False


In [ ]:
vect1 = np.random.randn(4, 5)
print(vect1)
print(vect1.sum(axis = 0))
print(vect1.sum(axis = 1))
print(vect1)

[[-5.98269227e-01  2.82337430e-02  3.92746078e-01 -1.44169525e+00
   3.22839962e-04]
 [-1.04991168e+00 -2.29937498e-01 -1.28359884e+00 -2.71119174e+00
  -1.52241044e+00]
 [-1.41620705e+00  1.10854366e+00  1.13102858e+00  4.98600308e-01
   1.17902193e+00]
 [ 1.32268437e+00  1.85215451e+00 -8.92171982e-01  6.16860709e-01
  -1.12182200e+00]]
[-1.7417036   2.75899442 -0.65199616 -3.03742597 -1.46488768]
[-1.61866181 -6.7970502   2.50098743  1.7777056 ]
[[-5.98269227e-01  2.82337430e-02  3.92746078e-01 -1.44169525e+00
   3.22839962e-04]
 [-1.04991168e+00 -2.29937498e-01 -1.28359884e+00 -2.71119174e+00
  -1.52241044e+00]
 [-1.41620705e+00  1.10854366e+00  1.13102858e+00  4.98600308e-01
   1.17902193e+00]
 [ 1.32268437e+00  1.85215451e+00 -8.92171982e-01  6.16860709e-01
  -1.12182200e+00]]


# Broadcasting



In [ ]:
a1 = np.array([[  0,  0,  0],
               [ 10, 10, 10],
               [ 20, 20, 20],
               [ 30, 30, 30]])
a2 = np.array([[0], [10], [20], [30]])
b1 = np.array([[0, 1, 2],
               [0, 1, 2],
               [0, 1, 2],
               [0, 1, 2]])
b2 = np.array([ 0, 1, 2])
print(a1, a1.shape)
print(a2, a2.shape)
print(b1, b1.shape)
print(b2, b2.shape)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] (4, 3)
[[ 0]
 [10]
 [20]
 [30]] (4, 1)
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]] (4, 3)
[0 1 2] (3,)


In [ ]:
print(a1 + b1)
print(a1 + b2)
print(a2 + b1)
print(a2 + b2)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
print(np.add(a1, b1))
print(np.add(a1, b2))
print(np.add(a2, b1))
print(np.add(a2, b2))

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
print(np.multiply(a1, b1))
print(np.multiply(a1, b2))
print(np.multiply(a2, b1))
print(np.multiply(a2, b2))

[[ 0  0  0]
 [ 0 10 20]
 [ 0 20 40]
 [ 0 30 60]]
[[ 0  0  0]
 [ 0 10 20]
 [ 0 20 40]
 [ 0 30 60]]
[[ 0  0  0]
 [ 0 10 20]
 [ 0 20 40]
 [ 0 30 60]]
[[ 0  0  0]
 [ 0 10 20]
 [ 0 20 40]
 [ 0 30 60]]
